name: flutter_firebase_auth_facade
description: A package to add instantly the authentication methods from firebase
version: 0.0.12-nullsafety.1
homepage: https://github.com/arnaudelub/flutter_packages/tree/main/flutter_firebase_auth_facade

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  dartz: ^0.10.0-nullsafety.1
  injectable: ^1.2.2
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  http: ^0.13.1
  #social Login
  google_sign_in: ^5.0.2
  sign_in_with_apple: ^3.0.0
  url_launcher: ^6.0.3
  uni_links2: ^0.6.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  very_good_analysis: ^2.0.3
  freezed: ^0.14.1+2
  json_serializable: ^4.1.1
  mocktail: ^0.1.1
  firebase_auth_mocks: ^0.6.0
  google_sign_in_mocks: ^0.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
